### ISSUE TITLE
openssl 3.0.0 compatible tpm2-tools version

### ISSUE THREAD

**Issue by satya-rajesh** [tpm2-software/tpm2-tools#2354]
While compiling observed that tpm2-tools is not compatible with openssl 3.0.0.

tpm2-tools is using deprecated APIs which are not present in openssl 3.0.0 (alpha).

Build status:
Build Failed due to RSA_*, HMAC_*, EC_*, ECDH_* deprecated APIs

Please provide tpm2-tools release compatible to openssl 3.0.0

**Comment by satya-rajesh** [comment]
Error logs (when build with openssl-3.0.0-alpha14):

In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from ACT_spt.c:73:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from ACTCommands.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from AlgorithmCap.c:67:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from AlgorithmTests.c:66:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from AttestationCommands.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from ClockCommands.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from BnConvert.c:67:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from AsymmetricCommands.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from AuditCommands.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CommandDispatcher.c:78:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptDes.c:66:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from Attest_spt.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from BnMemory.c:66:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptCmac.c:69:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from ContextCommands.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: ACTCommands.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [makefile:88: ACT_spt.o] Error 1
make: *** [makefile:88: AlgorithmCap.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptEccData.c:63:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CommandCodeAttributes.c:66:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptPrime.c:66:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: ClockCommands.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from BnMath.c:85:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: BnConvert.o] Error 1
make: *** [makefile:88: AuditCommands.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptPrimeSieve.c:64:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CommandAudit.c:66:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: AlgorithmTests.o] Error 1
make: *** [makefile:88: AsymmetricCommands.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptEccKeyExchange.c:63:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from Context_spt.c:63:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptEccMain.c:64:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from Bits.c:69:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CapabilityCommands.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: AttestationCommands.o] Error 1
make: *** [makefile:88: ContextCommands.o] Error 1
make: *** [makefile:88: BnMemory.o] Error 1
make: *** [makefile:88: Attest_spt.o] Error 1
make: *** [makefile:88: CryptDes.o] Error 1
make: *** [makefile:88: CryptCmac.o] Error 1
make: *** [makefile:88: CommandDispatcher.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptHash.c:67:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: CryptEccData.o] Error 1
make: *** [makefile:88: CommandCodeAttributes.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptEccSignature.c:64:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: CommandAudit.o] Error 1
make: *** [makefile:88: CryptPrimeSieve.o] Error 1
make: *** [makefile:88: Context_spt.o] Error 1
make: *** [makefile:88: Bits.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptSelfTest.c:73:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptRsa.c:69:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: CryptHash.o] Error 1
make: *** [makefile:88: CapabilityCommands.o] Error 1
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptRand.c:62:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
In file included from BnValues.h:324,
                 from Global.h:80,
                 from Tpm.h:78,
                 from CryptSmac.c:69:
TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
   79 | #   error Untested OpenSSL version
      |     ^~~~~
make: *** [makefile:88: CryptSelfTest.o] Error 1
make: *** [makefile:88: BnMath.o] Error 1
make: *** [makefile:88: CryptPrime.o] Error 1
make: *** [makefile:88: CryptEccKeyExchange.o] Error 1
make: *** [makefile:88: CryptRand.o] Error 1
make: *** [makefile:88: CryptRsa.o] Error 1
make: *** [makefile:88: CryptSmac.o] Error 1
make: *** [makefile:88: CryptEccMain.o] Error 1
make: *** [makefile:88: CryptEccSignature.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.j6frEy (%build)

**Comment by satya-rajesh** [comment]
compiled against openssl-3.0.0-alpha17, below are the errors observed:

lib/tpm2_openssl.c: In function 'tpm2_openssl_halg_to_digester':
lib/tpm2_openssl.c:358:16: error: 'SHA1' undeclared (first use in this function)
  358 |         return SHA1;
      |                ^~~~
lib/tpm2_openssl.c:358:16: note: each undeclared identifier is reported only once for each function it appears in
lib/tpm2_openssl.c:360:16: error: 'SHA256' undeclared (first use in this function); did you mean 'SHA256_CTX'?
  360 |         return SHA256;
      |                ^~~~~~
      |                SHA256_CTX
lib/tpm2_openssl.c:362:16: error: 'SHA384' undeclared (first use in this function)
  362 |         return SHA384;
      |                ^~~~~~
lib/tpm2_openssl.c:364:16: error: 'SHA512' undeclared (first use in this function); did you mean 'SHA512_CTX'?
  364 |         return SHA512;
      |                ^~~~~~
      |                SHA512_CTX
  CC       tools/tpm2_setprimarypolicy.o
  CC       tools/tpm2_createprimary.o
make: *** [Makefile:4845: lib/lib_libcommon_a-tpm2_openssl.o] Error 1
make: *** Waiting for unfinished jobs....
  CC       tools/tpm2_dictionarylockout.o

**Comment by satya-rajesh** [comment]
please suggest in which release can the openssl 3.0.0 support be expected ?

**Comment by idesai** [comment]
Fixed in 5.2
