### PR TITLE
Including inttypes.h on tpm2_checkquote

### PR DESCRIPTION
**Pull request by ramonssarmento**
I had this error when i tried to install:

> In file included from tools/misc/tpm2_checkquote.c:12:0:
> tools/misc/tpm2_checkquote.c: In function 'parse_selection_data_from_file':
> tools/misc/tpm2_checkquote.c:270:84: error: expected ')' before 'PRIu64'
>          LOG_ERR("Malformed PCR file, pcr count cannot be greater than %zu, got: %" PRIu64 " ",
>                                                                                     ^
> ./lib/log.h:29:69: note: in definition of macro 'LOG_ERR'
>  #define LOG_ERR(fmt, ...) _log(log_level_error, __FILE__, __LINE__, fmt, ##__VA_ARGS__)
>                                                                      ^
> tools/misc/tpm2_checkquote.c:270:17: error: format '%zu' expects a matching 'size_t' argument [-Werror=format=]
>          LOG_ERR("Malformed PCR file, pcr count cannot be greater than %zu, got: %" PRIu64 " ",
>                  ^
> ./lib/log.h:29:69: note: in definition of macro 'LOG_ERR'
>  #define LOG_ERR(fmt, ...) _log(log_level_error, __FILE__, __LINE__, fmt, ##__VA_ARGS__)
>                                                                      ^
> tools/misc/tpm2_checkquote.c:270:17: error: spurious trailing '%' in format [-Werror=format=]
>          LOG_ERR("Malformed PCR file, pcr count cannot be greater than %zu, got: %" PRIu64 " ",
>                  ^
> ./lib/log.h:29:69: note: in definition of macro 'LOG_ERR'
>  #define LOG_ERR(fmt, ...) _log(log_level_error, __FILE__, __LINE__, fmt, ##__VA_ARGS__)
>                                                                      ^
> cc1: all warnings being treated as errors
> Makefile:3588: recipe for target 'tools/misc/tools_tpm2-tpm2_checkquote.o' failed
> make: *** [tools/misc/tools_tpm2-tpm2_checkquote.o] Error 1

I supose it was caused by #2238 and i managed to solve this by including inttypes.h on tpm2_checkquote.

### CODE REVIEW

File: tools/misc/tpm2_checkquote.c [hunk 1]
```diff
@@ -5,7 +5,9 @@
 #include <stdlib.h>
 #include <string.h>
```
Comment (idesai) [inline tools/misc/tpm2_checkquote.c:7]: An empty line is not required here.
```suggestion
```

File: tools/misc/tpm2_checkquote.c [hunk 2]
```diff
@@ -5,7 +5,9 @@
...
 
- #include <openssl/pem.h>
+#include <inttypes.h>
```
Comment (idesai) [inline tools/misc/tpm2_checkquote.c:8]: Group this with other C standard headers and add this to the top to list them alphabetically.

**Review by idesai — CHANGES_REQUESTED** [review]

**Review by idesai — CHANGES_REQUESTED** [review]
@ramonssarmento, this looks good. Can you please squash the 3 commits and also signoff.
You could do the following:
```bash
git reset HEAD~2
git add --all
git commit -s
```

**Review by idesai — CHANGES_REQUESTED** [review]
Thank you @ramonssarmento. This still shows 2 commits.
Since your PR proposes one change, it should be a single commit.
Do this
```bash
git reset HEAD~1
git add --all
git commit --amend --no-edit --date=now
```

**Comment by ramonssarmento** [comment]
> 
> 
> @ramonssarmento, this looks good. Can you please squash the 3 commits and also signoff.
> You could do the following:
> 
> ```shell
> git reset HEAD~2
> git add --all
> git commit -s
> ```

Done

> 
> 
> Thank you @ramonssarmento. This still shows 2 commits.
> Since your PR proposes one change, it should be a single commit.
> Do this
> 
> ```shell
> git reset HEAD~1
> git add --all
> git commit --amend --no-edit --date=now
> ```

Holly, its still wrong, right?

**Comment by idesai** [comment]
> > @ramonssarmento, this looks good. Can you please squash the 3 commits and also signoff.
> > You could do the following:
> > ```shell
> > git reset HEAD~2
> > git add --all
> > git commit -s
> > ```
> 
> Done
> 
> > Thank you @ramonssarmento. This still shows 2 commits.
> > Since your PR proposes one change, it should be a single commit.
> > Do this
> > ```shell
> > git reset HEAD~1
> > git add --all
> > git commit --amend --no-edit --date=now
> > ```
> 
> Holly, its still wrong, right?

Yes, the PR still has some redundant commits. I will take your changes and apply your commit via #2245 which lists you as the author.

Thanks for the PR.

**Comment by idesai** [comment]
Closed via #2245
